### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by mchu011** [oribix/lab5#1]
what happened to the get and push part of the code?
I remember we finished that part on Monday.

**Comment by mchu011** [comment]
finished method 3's code, having difficulty figuring out method 2's code

**Comment by oribix** [comment]
I finished method 2's code. also I posted the wrong code

I was just going to do the whole thing by myself. I didnt want to bother you. Well if you finished he code, I could probably take your code and add it to mine then push it to my clone of your rshell (wow that was a complicated sentence).

**Comment by oribix** [comment]
I was just going to do the whole assignment by myself

**Comment by oribix** [comment]
give me a second.

**Comment by mchu011** [comment]
made a pull request for including in method 3

**Comment by oribix** [comment]
uuuuuuuuuh wut

**Comment by oribix** [comment]
i pushed to my clone of your rshell. I am going to add this code to the clone and make a pull request.

**Comment by oribix** [comment]
we should be mostly done after that.

**Comment by mchu011** [comment]
okay, are you going to be at the TA's office hours at 2?

**Comment by oribix** [comment]
yeah. Also, you forgot to do error checking on close and open. Remember to do those. I already fixed them. I am about to compile and test. If it works, I am going to push to my clone then make a pull request. wish me luck.

**Comment by oribix** [comment]
Im going to make a pull request now. The file isnt done yet. it still needs the timer. im going to add it then make one more pull request.

**Comment by mchu011** [comment]
okay

**Comment by oribix** [comment]
request is up. I am going to work on the timers. should only take like 10 minutes. ill make another request then. Go to sleep if you want to . We can finish uploading to github tomorrow.

**Comment by mchu011** [comment]
okay, 'night
